openapi: 3.0.0
info:
  title: cosslan API
  version: 1.0.0
paths:
  /api/v1/node/:
    get:
      summary: Say Hello
      operationId: node
      tags:
        - node
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: string