components:
    schemas:
        CreateNetwork:
            properties:
                address:
                    description: 网络地址
                    example: 192.168.1.0
                    type: string
                subnet_mask:
                    description: 子网掩码
                    example: 255.255.255.0
                    type: string
            type: object
        Response:
            properties:
                code:
                    type: integer
                    x-go-type-skip-optional-pointer: true
                    x-omitempty: false
                data:
                    type: object
                msg:
                    type: string
                    x-go-type-skip-optional-pointer: true
                    x-omitempty: false
            type: object
        UserLoginRequest:
            properties:
                email:
                    format: email
                    type: string
                    x-go-type-skip-optional-pointer: true
                    x-omitempty: false
                password:
                    type: string
                    x-go-type-skip-optional-pointer: true
                    x-omitempty: false
            required:
                - email
                - password
            type: object
    securitySchemes:
        BearerAuth:
            bearerFormat: JWT
            scheme: bearer
            type: http
info:
    title: cosslan API
    version: 1.0.0
openapi: 3.0.0
paths:
    /api/v1/line/:
        get:
            operationId: line
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: string
                    description: A successful response
            summary: Say Hello
            tags:
                - line
    /api/v1/network:
        post:
            operationId: createNetwork
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateNetwork'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response'
                    description: Network created successfully
            summary: 创建网络
            tags:
                - network
    /api/v1/node/:
        get:
            operationId: node
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: string
                    description: A successful response
            summary: Say Hello
            tags:
                - node
    /api/v1/user/login:
        post:
            operationId: login
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserLoginRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response'
                    description: 登录成功
            security:
                - BearerAuth: []
            summary: 用户登录
            tags:
                - user
